import type { ShopItemDef } from '../../core/types';

/** Koban economy and shop rules */
export const SHOP_RULES = {
  maxItems: 4,
  sellReturn: 0.5,
  koban: { kill: 120, assist: 60, objTick: 5, objInterval: 2, dmgPerKoban: 25, healPerKoban: 12, bonus: 150 },
};

export const SHOP_ITEMS: ShopItemDef[] = [
  { id: "vigor",            name: "Vigor",               category: "Health",      description: "Aumenta a vida máxima.",                                    icon: "❤", levels: 4, costs: [300, 450, 650, 900], mods: [{ maxHp: 0.05 }, { maxHp: 0.10 }, { maxHp: 0.15 }, { maxHp: 0.20 }] },
  { id: "protecao",         name: "Proteção Espiritual", category: "Dmg Resist",  description: "Reduz o dano recebido.",                                     icon: "🛡", levels: 4, costs: [300, 450, 650, 900], mods: [{ dmgResist: 0.04 }, { dmgResist: 0.08 }, { dmgResist: 0.12 }, { dmgResist: 0.16 }] },
  { id: "escudo",           name: "Escudo Ancestral",    category: "Shield",      description: "Aumenta escudo recebido ou gerado.",                          icon: "⛨", levels: 4, costs: [250, 400, 550, 750], mods: [{ shieldMult: 0.05 }, { shieldMult: 0.10 }, { shieldMult: 0.15 }, { shieldMult: 0.20 }] },
  { id: "bencao",           name: "Bênção da Miko",      category: "Healing",     description: "Aumenta a cura realizada.",                                    icon: "✚", levels: 4, costs: [250, 400, 550, 750], mods: [{ healMult: 0.05 }, { healMult: 0.10 }, { healMult: 0.15 }, { healMult: 0.20 }] },
  { id: "vinganca",         name: "Vingança do Ronin",   category: "Elimination", description: "Recupera vida ao eliminar um inimigo.",                       icon: "⚔", levels: 4, costs: [300, 450, 650, 900], mods: [{ onKillHeal: 0.03 }, { onKillHeal: 0.06 }, { onKillHeal: 0.09 }, { onKillHeal: 0.12 }] },
  { id: "tengu",            name: "Passos do Tengu",     category: "Movement",    description: "Velocidade temporária após eliminar.",                          icon: "💨", levels: 4, costs: [250, 400, 550, 750], mods: [{ onKillSpeed: 0.10, onKillSpeedDur: 2 }, { onKillSpeed: 0.15, onKillSpeedDur: 2 }, { onKillSpeed: 0.20, onKillSpeedDur: 2 }, { onKillSpeed: 0.25, onKillSpeedDur: 2 }] },
  { id: "fluxo",            name: "Fluxo de Ki",         category: "Cooldown",    description: "Reduz recarga das habilidades.",                               icon: "⏳", levels: 4, costs: [300, 450, 650, 900], mods: [{ cooldownMult: -0.05 }, { cooldownMult: -0.10 }, { cooldownMult: -0.15 }, { cooldownMult: -0.20 }] },
  { id: "nucleo",           name: "Núcleo Espiritual",   category: "Resource",    description: "Aumenta geração de recurso (ultimate).",                        icon: "🔮", levels: 4, costs: [250, 400, 550, 750], mods: [{ resourceGain: 0.05 }, { resourceGain: 0.10 }, { resourceGain: 0.15 }, { resourceGain: 0.20 }] },
  { id: "laminada",         name: "Lâmina Afiada",       category: "Offense",     description: "Aumenta o dano causado.",                                       icon: "🗡", levels: 4, costs: [300, 450, 650, 900], mods: [{ damageMult: 0.04 }, { damageMult: 0.08 }, { damageMult: 0.12 }, { damageMult: 0.16 }] },
  { id: "pontaria",         name: "Pontaria do Mestre",  category: "Offense",     description: "Aumenta o dano de acerto crítico.",                             icon: "🎯", levels: 4, costs: [250, 400, 550, 750], mods: [{ headshotMult: 0.10 }, { headshotMult: 0.20 }, { headshotMult: 0.30 }, { headshotMult: 0.40 }] },
  { id: "carregador",       name: "Carregador Ampliado", category: "Offense",     description: "Aumenta a munição máxima.",                                     icon: "📦", levels: 4, costs: [200, 350, 500, 700], mods: [{ ammoMult: 0.15 }, { ammoMult: 0.30 }, { ammoMult: 0.45 }, { ammoMult: 0.60 }] },
  { id: "recarga",          name: "Recarga Rápida",      category: "Offense",     description: "Reduz o tempo de recarga da arma.",                             icon: "🔁", levels: 4, costs: [200, 350, 500, 700], mods: [{ reloadMult: -0.10 }, { reloadMult: -0.20 }, { reloadMult: -0.30 }, { reloadMult: -0.40 }] },
  { id: "folego",           name: "Fôlego do Guerreiro", category: "Movement",    description: "Aumenta a altura de pulo.",                                      icon: "🦘", levels: 4, costs: [200, 350, 500, 700], mods: [{ jumpPower: 0.05 }, { jumpPower: 0.10 }, { jumpPower: 0.15 }, { jumpPower: 0.20 }] },
  { id: "agilidade",        name: "Agilidade do Ninja",  category: "Movement",    description: "Aumenta a velocidade de movimento.",                             icon: "👟", levels: 4, costs: [250, 400, 550, 750], mods: [{ moveSpeed: 0.05 }, { moveSpeed: 0.10 }, { moveSpeed: 0.15 }, { moveSpeed: 0.20 }] },
  { id: "precisao",         name: "Mira de Precisão",    category: "Offense",     description: "Reduz a dispersão da arma.",                                     icon: "◎", levels: 4, costs: [200, 350, 500, 700], mods: [{ spreadMult: -0.10 }, { spreadMult: -0.20 }, { spreadMult: -0.30 }, { spreadMult: -0.40 }] },
  { id: "velocidade",       name: "Projéteis Velozes",   category: "Offense",     description: "Aumenta a velocidade dos projéteis.",                            icon: "➤", levels: 4, costs: [200, 350, 500, 700], mods: [{ projSpeed: 0.10 }, { projSpeed: 0.20 }, { projSpeed: 0.30 }, { projSpeed: 0.40 }] },
  { id: "sangue",           name: "Sangue do Samurai",   category: "Elimination", description: "Rouba vida ao causar dano.",                                    icon: "🩸", levels: 4, costs: [300, 450, 650, 900], mods: [{ lifesteal: 0.03 }, { lifesteal: 0.06 }, { lifesteal: 0.09 }, { lifesteal: 0.12 }] },
  { id: "forca",            name: "Força do Oni",        category: "Offense",     description: "Aumenta o dano corpo a corpo.",                                  icon: "👊", levels: 4, costs: [250, 400, 550, 750], mods: [{ meleeDamageMult: 0.10 }, { meleeDamageMult: 0.20 }, { meleeDamageMult: 0.30 }, { meleeDamageMult: 0.40 }] },
  { id: "ampulheta",        name: "Ampulheta Espiritual", category: "Ultimate",   description: "Aumenta a carga do ultimate.",                                   icon: "⏱", levels: 4, costs: [250, 400, 550, 750], mods: [{ ultGain: 0.10 }, { ultGain: 0.20 }, { ultGain: 0.30 }, { ultGain: 0.40 }] },
  { id: "raio",             name: "Raio Ampliado",       category: "Ability",     description: "Aumenta o raio das habilidades de área.",                        icon: "⭕", levels: 4, costs: [250, 400, 550, 750], mods: [{ abilityRadius: 0.10 }, { abilityRadius: 0.20 }, { abilityRadius: 0.30 }, { abilityRadius: 0.40 }] },
];
